CREATE TABLE account (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    login         VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT uk_account_login UNIQUE (login),
    CONSTRAINT uk_account_email UNIQUE (email),
    CONSTRAINT ck_account_login_lowercase CHECK (login = lower(login)),
    CONSTRAINT ck_account_email_lowercase CHECK (email = lower(email))
);

CREATE TABLE account_creation_request (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    login            VARCHAR(50)  NOT NULL,
    password_hash    VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    validation_token VARCHAR(36)  NOT NULL,
    CONSTRAINT pk_account_creation_request PRIMARY KEY (id),
    CONSTRAINT uk_account_creation_request_login UNIQUE (login),
    CONSTRAINT uk_account_creation_request_email UNIQUE (email),
    CONSTRAINT uk_account_creation_request_validation_token UNIQUE (validation_token),
    CONSTRAINT ck_account_creation_request_login_lowercase CHECK (login = lower(login)),
    CONSTRAINT ck_account_creation_request_email_lowercase CHECK (email = lower(email))
);

CREATE TABLE room (
    id                            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name                          VARCHAR(100) NOT NULL,
    location                      VARCHAR(255) NOT NULL,
    capacity                      INTEGER      NOT NULL,
    type                          VARCHAR(20)  NOT NULL,
    description                   VARCHAR(500),
    reservation_requires_approval BOOLEAN      NOT NULL,
    CONSTRAINT pk_room PRIMARY KEY (id),
    CONSTRAINT uk_room_name UNIQUE (name),
    CONSTRAINT ck_room_capacity_positive CHECK (capacity > 0)
);

CREATE TABLE equipment (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    room_id     BIGINT       NOT NULL,
    CONSTRAINT pk_equipment PRIMARY KEY (id),
    CONSTRAINT fk_equipment_room FOREIGN KEY (room_id) REFERENCES room (id)
);

CREATE TABLE availability_slot (
    id       BIGINT    GENERATED BY DEFAULT AS IDENTITY,
    start_at TIMESTAMP NOT NULL,
    end_at   TIMESTAMP NOT NULL,
    room_id  BIGINT    NOT NULL,
    CONSTRAINT pk_availability_slot PRIMARY KEY (id),
    CONSTRAINT fk_availability_slot_room FOREIGN KEY (room_id) REFERENCES room (id),
    CONSTRAINT ck_availability_slot_period CHECK (end_at > start_at)
);

CREATE TABLE reservation (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    start_at     TIMESTAMP    NOT NULL,
    end_at       TIMESTAMP    NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    purpose      VARCHAR(500) NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    room_id      BIGINT       NOT NULL,
    requester_id BIGINT       NOT NULL,
    CONSTRAINT pk_reservation PRIMARY KEY (id),
    CONSTRAINT fk_reservation_room FOREIGN KEY (room_id) REFERENCES room (id),
    CONSTRAINT fk_reservation_requester FOREIGN KEY (requester_id) REFERENCES account (id),
    CONSTRAINT ck_reservation_period CHECK (end_at > start_at)
);
