spring.application.name=room-management-system

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
spring.datasource.username=${PG_USER}
spring.datasource.password=${PG_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}

app.mail.from=${MAIL_FROM}
app.mail.validation-url=${APP_VALIDATION_URL}

spring.mvc.problemdetails.enabled=true
server.servlet.context-path=/api

# springdoc.swagger-ui.enabled=false
# springdoc.api-docs.enabled=false
